### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by jmeyer90** [rgltalatala/Ravebrite#1]
# MVPs
1. Include specific CRUD functionality for Events

# Schema
1. For user associations, we should have many hosted events, have many registered events through registrations, and have many bookmarked events through bookmarks.
2. For events associations, we should have many registrations and have many attendees through registrations.
3. For registration/ticket associations, we should rename ticket_owner to attendee for consistency

# Sample State
1. Consider adding modals to your UI slice of Redux state.
2. Add other back-end entities other than just events and users.

# Back-End Routes
1. Registration routes should be restructured to:
    GET /api/users/:user_id/registrations shows all registered events for current user
    POST /api/events/:event_id/registrations add registration
    DELETE /api/registration/:id delete registration
2. Bookmark delete route should be changed to:
    DELETE /api/bookmarks/:id - remove a bookmarked event
3. Categories are stored under events. We do not need any back-end routes for categories. This information would be included with event routes.

# Front-End Routes & Components
1. Beak down the components into their sub-components as well. Become very modular and think about what sub-components you'll need to create when building out your application.

**Comment by rgltalatala** [comment]
Hi Justin,

I've gone ahead and implemented the suggestions you've provided to my wiki.  Please let me know if you have any more suggestions to make.  

I wanted to ask if it would be a good idea to combine registrations and bookmarks into one table because both have the same data columns of an id, user_id, and event_id.  I was thinking I can have an additional column of type string or boolean that could dictate whether the table is being used for registrations or bookmarks for a specific instance.  I was thinking it would make my code a bit more DRY but unsure if it would complicate things.  Please let me know your thoughts!

**Comment by jmeyer90** [comment]
Hi Raphael,

There are several ways to handle the registrations and bookmarks. The biggest hurdle towards combining these would be our associations and differentiating between registrations and bookmarks when we send data up to the front-end. For our use case, I'd say it's fine as is. But this can be a refactor you can do later on.

Documentation looks great!
